=== Arun-purakkatt/qeschema/qeschema/schemas/xspectra_short.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
Source: https://github.com/QEF/q-e/blob/master/XSpectra/Doc/INPUT_XSPECTRA
Authors: Gianfranco Abrusci
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:qes_xspectra="http://www.quantum-espresso.org/ns/qes/xspectra"
	targetNamespace="http://www.quantum-espresso.org/ns/qes/xspectra" version="20220120">
    <element name="xspectra" type="qes_xspectra:xspectra"/>
    <complexType name="input">
        <sequence>
            <element name="input_xspectra" type="qes_xspectra:input_xspectra" />
            <element name="plot" type="qes_xspectra:plot"/>
            <element name="pseudos" type="qes_xspectra:pseudos"/>
            <element name="cut_occ" type="qes_xspectra:cut_occ"/>
            <element name="kpoints" type="qes_xspectra:kpoints"/>
        </sequence>
    </complexType>

    <complexType name="input_xspectra" >
        <sequence>
            <element name="calculation" type="string"   minOccurs="1" maxOccurs="1"  default=""/>
            <element name="edge"        type="string"   minOccurs="0" maxOccurs="1"  default="K"/>
        </sequence>
    </complexType>

    <complexType name="plot">
        <sequence>
            <element name="xnepoint"    type="integer"  minOccurs="0" maxOccurs="1"  default="100"/>
        </sequence>
    </complexType>


    <complexType name="pseudos">
        <sequence>
            <element name="filecore"    type="string"   minOccurs="0" maxOccurs="1"  default="Core.wfc"/>
        </sequence>
    </complexType>

    <complexType name="cut_occ">
        <sequence>
            <element name="cut_ierror"   type="double"   minOccurs="0" maxOccurs="1"  default="1.d-7"/>
        </sequence>
    </complexType>
    <complexType name="kpoints">
        <sequence>
            <element name="tmp_kpoint" type="string" minOccurs="1" maxOccurs="1"/>
        </sequence>
    </complexType>

</schema>

=== Arun-purakkatt/qeschema/tests/resources/xspectra/xspectra_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<qes_xspectra:xspectra xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes_xspectra-1.0 xspectra_short.xsd"
               xmlns:qes_xspectra="http://www.quantum-espresso.org/ns/qes/qes_xspectra-1.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	       <input>	       
      <input_xspectra>
        <calculation>xanes_dipole</calculation>
        <edge>L2</edge>
      </input_xspectra>
      <plot>
        <xnepoint>100</xnepoint>
      </plot>
      <pseudos>
        <filecore>Core.wfc</filecore>
      </pseudos>
      <cut_occ>
      </cut_occ>
      <kpoints>
        <tmp_kpoint>0 0 0</tmp_kpoint>
      </kpoints>
</input>
</qes_xspectra:xspectra>
